config/routes.rb
Rails.application.routes.draw do
  resources :sections do
    resources :subsections, :only => [] do
      resources :lessons
    end
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :subsection

  validates :name, :presence => true

  define_method(:next_lesson) do
     if self == subsection.lessons.last
       if subsection == subsection.section.subsections.last
         if subsection.section == Section.last
           return nil
         else
           next_section = Section.find(subsection.section_id + 1)
           return next_section.subsections.first.lessons.first
         end
       else
         next_subsection = Subsection.find(self.subsection_id + 1)
         return next_subsection.lessons.first
       end
     else
       Lesson.find(self.id + 1)
     end
  end

  define_method(:previous_lesson) do
    if self == subsection.lessons.first
      if subsection == subsection.section.subsections.first
        if subsection.section == Section.first
          return nil
        else
          previous_section = Section.find(subsection.section_id - 1)
          return previous_section.subsections.last.lessons.last
        end
      else
        previous_subsection = Subsection.find(self.subsection_id - 1)
        return previous_subsection.lessons.last
      end
    else
      Lesson.find(self.id - 1)
    end
  end

end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :subsections

  validates :name, :presence => true
end

app/models/subsection.rb
class Subsection < ActiveRecord::Base
  belongs_to :section
  has_many :lessons

  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
    @lesson = Lesson.find(params[:id])
    @next_lesson = @lesson.next_lesson
    if @next_lesson == nil
      @next_lesson = Lesson.first
      @next_subsection = Subsection.first
      @next_section = Section.first
    else
        @next_subsection = Subsection.find(@next_lesson.subsection_id)
        @next_section = Section.find(@next_subsection.section_id)
    end
    @previous_lesson = @lesson.previous_lesson
    if @previous_lesson == nil
      @previous_lesson = Lesson.last
      @previous_subsection = Subsection.last
      @previous_section = Section.last
    else
      @previous_subsection = Subsection.find(@previous_lesson.subsection_id)
      @previous_section = Section.find(@previous_subsection.section_id)
    end
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      flash[:notice] = "Section successfully added!"
      redirect_to sections_path
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(params[:section])
      flash[:notice] = "Section successfully updated!"
      redirect_to sections_path
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] = "Section successfully destroyed!"
    redirect_to sections_path
  end

  private
  def section_params
    params.require(:section).permit(:name)
  end
end

app/controllers/subsections_controller.rb
class SubsectionsController < ApplicationController
  def index
    @section = Section.find(params[:section_id])
    @subsections = @section.subsections
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="/app/assets/stylesheets/bootstrap.min.css"></link>
</head>
<body>
  <div class="container">

    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </div>
</body>
</html>

app/views/lessons/show.html.erb
<% @title = @lesson.name %>

<h1><%= @lesson.name %></h1>

<div class="bottom">
  <button><%= link_to 'Previous Lesson', section_subsection_lesson_path(@next_section, @next_subsection, @next_lesson)%></button>
  <button><%= link_to 'Next Lesson', section_subsection_lesson_path(@next_section, @next_subsection, @next_lesson)%></button>
</div>
<div id="bottom-right">
  <button><%= link_to 'Table of Contents', sections_path()%></button>
</div>

app/views/sections/index.html.erb
<% @title = 'Table of Contents'%>
<h1>Table of contents</h1>

  <ul>
    <% @sections.each do |section| %>
      <div class="col-sm-6 ">
        <li><h5><%= section.name %></h5></li>
        <ul>
          <% section.subsections.each do |subsection| %>
          <div class="subsection">
            <li><%= subsection.name %></li>
              <ul>
                <% subsection.lessons.each do |lesson| %>
                <li class="lessons"><%= link_to lesson.name, section_subsection_lesson_path(section,subsection,lesson) %></li>
                <% end %>
              </ul>
          </div>
          <% end %>
        </ul>
      </div>
    <% end %>
  </ul>

  <script>
  $(document).ready(function() {
    $(".subsection").hover(function(event) {
      $(this).children().children().show();
      event.preventDefault();
    });
  });
  </script>